from ..urls import HANDBOOKS_API_URL

STREET_URL = f'{HANDBOOKS_API_URL}/streets'
DISTRICT_URL = f'{HANDBOOKS_API_URL}/districts'
REGION_URL = f'{HANDBOOKS_API_URL}/regions'
CITY_URL = f'{HANDBOOKS_API_URL}/cities'
CITY_REGION_URL = f'{HANDBOOKS_API_URL}/city_regions'
HANDBOOK_URL = f'{HANDBOOKS_API_URL}/handbooks'
NEW_BUILDING_URL = f'{HANDBOOKS_API_URL}/new_buildings'
CLIENT_URL = f'{HANDBOOKS_API_URL}/clients'
