# Generated by Django 4.2.5 on 2023-09-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('ru', models.CharField(max_length=150)),
                ('en', models.CharField(max_length=150)),
                ('uk', models.CharField(max_length=150)),
            ],
        ),
    ]
